### PR TITLE
Added post endpoint for updating an order.

### PR DESCRIPTION
**Pull request by zkimffm**
Added a post endpoint to update an order.

Example usage:
```
$body = [
    'entity' => [
        'entity_id' => '12345',
        'extension_attributes' => [
            'amasty_order_attributes' => [
                'delivery_date' => '2021-09-07'
            ]
        ]
    ]
];
```
`...api('orders')->edit($body);`

### CODE REVIEW

**Comment by ahinkle** [comment]
Thanks, @zkimffm!

What are your thoughts on removing the parent-level `entity` array? Will there ever be anything else passed besides `entity`?
 
e.g. 
```php
Magento::api('orders')->edit([
    'entity_id' => '12345',
    'extension_attributes' => [
        'amasty_order_attributes' => [
            'delivery_date' => '2021-09-07'
        ]
    ]
    // so on so forth..
]);
```

**Comment by ahinkle** [comment]
Hey @zkimffm ,

Right :) I'm saying what if we automatically provide `entity` in the array so the developer doesn't have to write it every time.

it would change the method to something like this:

```php
public function edit($entity = [])
{
    return $this->post('/orders', [
        'entity => $entity',
    ]);
}
```

then, you don't have to provide `entity`:
```php
Magento::api('orders')->edit([
    'entity_id' => '12345',
    'extension_attributes' => [
        'amasty_order_attributes' => [
            'delivery_date' => '2021-09-07'
        ]
    ]
    // so on so forth..
]);
```
Thoughts there, or would expect to write that out each time?

**Comment by zkimffm** [comment]
> Hey @zkimffm ,
> 
> Right :) I'm saying what if we automatically provide `entity` in the array so the developer doesn't have to write it every time.
> 
> it would change the method to something like this:
> 
> ```
> public function edit($entity = [])
> {
>     return $this->post('/orders', [
>         'entity => $entity',
>     ]);
> }
> ```
> 
> then, you don't have to provide `entity`:
> 
> ```
> Magento::api('orders')->edit([
>     'entity_id' => '12345',
>     'extension_attributes' => [
>         'amasty_order_attributes' => [
>             'delivery_date' => '2021-09-07'
>         ]
>     ]
>     // so on so forth..
> ]);
> ```
> 
> Thoughts there, or would expect to write that out each time?

Ah! @ahinkle I understand what you mean now. Okay, that sounds good. I will make the change! Thanks.

**Comment by ahinkle** [comment]
Thanks, @zkimffm!

**Pull request merged**
